Changing background image feature
German-Immersive-Railroading-Community/Launcher pull request #15
Opened 2021-07-01 18:03 UTC by codingbytimo

2021-07-01 18:23 UTC, Der-Zauberer commented on src/main/java/com/troblecodings/launcher/assets/style.css
> +	/*-fx-background-image: url(background.png);*/
Please remove the line, because we don't need this anymore!

2021-07-01 18:24 UTC, Der-Zauberer requested changes
Please remove the unused css line

2021-07-02 07:57 UTC, Der-Zauberer approved these changes

2021-07-02 11:06 UTC, MrTroble approved these changes

2021-07-02 12:35 UTC, merged